################## BASE IMAGE ######################

FROM ubuntu:latest

################## METADATA ######################

LABEL maintainer="Albert Cañellas <albert.canellas@bsc.es>" \
    container="AsiteDesign" \
    about.summary="design catalytic residues, perform in silico directed evolution of an existing active site." \
    about.home="https://github.com/masoudk/AsiteDesign" \
    software.version="5.0"

################## INSTALLATION ######################

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

# Update to latest packages
RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git zip gcc libopenmpi-dev python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=/home/AsiteDesign
ENV PATH=/home/AsiteDesign:$PATH

# Set the workind directory
WORKDIR /home

ARG CONDA_VERSION=py37_4.12.0
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-$(uname -s)-$(uname -m).sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

# Extra packages
RUN pip install biotite

# Install open-mpi
ARG OPENMPI_DIR=/opt/open-mpi-4.1.2
WORKDIR /opt/open-mpi
ARG OPENMPI_VERSION="4.1.2"
RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-${OPENMPI_VERSION}.tar.gz && \
    tar xfz openmpi-${OPENMPI_VERSION}.tar.gz && \
    cd openmpi-${OPENMPI_VERSION} && \
    ./configure && \
    make && \
    make install && \
    rm -rf /opt/open-mpi/openmpi-${OPENMPI_VERSION}.tar.gz

# Environment variables for openmpi
ENV PATH=${OPENMPI_DIR}/openmpi-${OPENMPI_VERSION}/bin:$PATH
ENV LD_LIBRARY_PATH=${OPENMPI_DIR}/openmpi-${OPENMPI_VERSION}/lib:$LD_LIBRARY_PATH
ENV MANPATH=${OPENMPI_DIR}/openmpi-${OPENMPI_VERSION}/share/man:$MANPATH

# Install conda packages
WORKDIR /home
RUN conda install -c omnia -c conda-forge biopython cython mpi4py pyyaml

#Install fftw
RUN wget http://www.fftw.org/fftw-3.3.10.tar.gz && \
    tar xfz fftw-* && \
    rm fftw-3.3.10.tar.gz && \
    cd fftw-3.3.10 && \
    ./configure && \
    make && \
    make install

# Install AsiteDesign
ADD AsiteDesign.tar /home