name: biobb_asitedesign
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python
  - biobb_common>=3.9.0
  - nb_conda_kernels
  - pytest
  - zip
  - conda
  - zlib
  - byobu
  - ncurses
  - bzip2
  - backports.lzma
  - libcurl
